### ISSUE TITLE
How to install ?

### ISSUE THREAD

**Issue by huukhoa1412** [Teru-dot-png/RG_Digimon#1]
Hello , i am newber . I dont install game. Can you guide the installation?

**Comment by Teru-dot-png** [comment]
its for RG cant install normally like a executable software

this is RG https://store.steampowered.com/app/1730260/Retro_Gadgets/
![image](https://user-images.githubusercontent.com/68662335/209910731-6aad9a49-adc7-4714-a704-e6c0162f03fe.png)
the code is still in alpha anyways digimon has one form from rn

but the steps should be simple:

1. have Retro Gadgets
2. put all the git files in the import located in "users/{User}/Documents/My Games/Retro/Import"
3. build the gadget specs as in the (README.md)
4. make sure the CPU has the game-script "main" in it and all files are named properly in game

that should be it if you wanna test it

❤️ anyways happy holidays!
